version: "3"
services:
  app:
    build: .
    image: dictionary-matrix
    restart: unless-stopped
    depends_on:
      - mongodb
      - naisc
    networks:
      - frontend
      - backend
    ports:
      - "8000:8000"
    volumes:
      - uploads:/uploads
      - naisc:/naisc
    environment:
      DEBUG: 'true'
      UPLOAD_PATH: '/uploads'
      SESSION_COOKIE_SECRET_KEY: "change me secret"
      MONGODB_CONNECTION_STRING: 'mongodb://mongodb'
      LINKING_NAISC_EXECUTABLE: '/naisc/naisc.sh'

  mongodb:
    image: mongo:4.4
    restart: unless-stopped
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

  naisc:
    build:
      context: .
      dockerfile: Dockerfile.naisc
    entrypoint: sh
    restart: unless-stopped
    volumes:
      - naisc:/naisc

networks:
  frontend:
    driver: bridge
  backend:

volumes:
  uploads:
  mongodbdata:
  naisc:
